on:
  push:
    tags:
    - "*"

name: release

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: "docker compose up --build --exit-code-from app"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./src/wasm/pkg/
      - run: "npm diff --tag=${{github.ref_name}}"
      - run: "[[ -z $(npm diff --tag=${{github.ref_name}}) ]]"